---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: budgetwise-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAXsIPhTymwiq9bGNfyOr8G+IoqB1T7+plOO+JWF7LG7nSmDqp29eE8jsKodDBgd6FYmqoZGAbOkAoXqRN2/S0pUr4G76mvCUbg9Spsamu+FEfM0TjWINiohRC353W2616Scpq5c6gc3M4hX69VeLAOzzMrKS06587DL4ciFI9TvZEzzbuSJL6cBsIpqoAl/vnlejYmyXjmW6MsYoa7CJ/iv/Hvydsj1Mp7fwnEWQ++6uZCPI5aQ74zWPNGaHLavD8qOr7Nci8B6RQOD61stH2KfKsHvaOvIMPrSpLplWUrHIez0+KrN5UKxsn4IUVkT2Nvelyz/Ig/6JI9XmllZM5czI75D4V96iFtzB1oMDu9QQ4iTZc75WLWU5U/JBHQoaAfSYrTZGjdBl7kXU1ZBWW5BMdXuwVFBvdRC8y28E3Q3bPbJ3jmnjh0udgP30QNs6d8gJe32nmpckaATyjydWbpNRA76Ihfm2Egq5EAf85KR4PXcR5b3z6kYri/zOXUo/MLbZjC77TB6uVKoq5C4/3fJmiaAs7MYroUcBFIvfhFTLNf5zP5egWKH5+r4GJdzuhaoZ1HTw8BEpB3f8XHyqmw0K6KZYWRxAahE/s98lMA8oPr+tGpuxZ7O70Tij+/90CGNGRl50WfBw+ZdefSbz7QYJP6frPKrZe1Wnp6J9B5vYb56bDWyehSr8dq7nihbuPtwQsHH5GlNft1kPIrB8YySP3/K35k7Ru4CfZvNWFtUCruBMRbpe8keLoIuEhXxeL7OWW1vBamFu5pRbv1boXE115y+crJSqdLJRXFM37hpgfnHe6/uEyda6BV0ZEzXlnOPzF32ZxOBMyEU8FMgGv+M4cDAa9W2cMRvJ0mcfF46fijbVLNBPBpaMvnNezuuYyDem4x2HPRV/80KuOxyGYHYkV6v3DZKTO9xu0o+cKDhQbzyfEMKxx9/3oK3KsXnFfzrdLm4UoZTHrR9qgdjLPx/q8mexNQ/h0sd15z
  template:
    metadata:
      name: ghcr-secret
      namespace: budgetwise-dev
    type: kubernetes.io/dockerconfigjson
