# Default values for budgetwise
replicaCount: 1

image:
  repository: ghcr.io/abiraahammed/budgetwise
  pullPolicy: Always
  tag: "main"

perfin:
  appName: "perfin"
  image:
    repository: ghcr.io/abiraahammed/perfin
    pullPolicy: Always
    tag: "main"
  service:
    port: 8080
  env:
    SPRING_DATASOURCE_URL: "jdbc:postgresql://10.0.0.245:5432/metrics"
imagePullSecrets:
  - name: ghcr-secret
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""
  imagePullSecrets:
    - name: ghcr-secret

sealedSecrets:
  ghcrSecret:
    name: ghcr-secret
    namespace: budgetwise
    type: kubernetes.io/dockerconfigjson
    encryptedData: 
      ".dockerconfigjson": "AgCUWNv1sypVCsOzT0muJxCzrHPlVcHMOMj0m39OGezQrzNf0iI4pqzh6QOs0HtBDKUMM4lUyKuEKt5CPGMGYwcAqm1Hy3pLXOfxSttnmIg0e82WRff2PNmK3RdNTkHtIP12yQd7vndihRkzOdW4XP+/KnncLGZ9Gw/MovXUgZum7cSMlmRaqFgpBIhIqtwkS9vYlG8hS/6KC6KaXB70RwKHzDo2l1FTyjcnK7XFPqIWANyaigan2lzzSlU5BnPYdZXKi4MywpO2saNQZD151ZfjM/HW4vP1gF0pYt+OcErNLbvf4VfUc1s7Ms3qibUFEsfFC5TTaCqlz/ykWmM4fYvEjO6ulxh6Iftnsd9n75KbSTTJAZzgj9becD3bhg/3R94dwDYqAVNBBDjG1nZ3rdoHhtAR6KwNDPSO9WZ7iaH1fLNag83GP4LEWvcaNO259JyebvhtPWruX+ks/NnkCxbdrlBHoIxEgayW2hDMAPQX8yEiBADtE40HynoCNerAOrX+9JzJ+5ea4XcKBkVAd4ov1PUPReJqByHQW0wdylcRcKsD8cvYQLfNyZimv1ZRJbutKhumfBehZEQPr/IUGjJRzYKPeNma1wLwOAJoxYFKq/kIvEGZ3bngsLuYjY3zUrAKg9M9w195BdtKKqi+JVRkZDVLxjpvK6ySOTqAy5J7UIiEixCEUxjK0MLkV5/2lpifI0LqJCgJpon/LlMFU1/13QDQQs+RwCX2SqofezkytPZClnVAdnBKlOkjRnPYhZzesEvI2C+Y6v6812DnY9WvADwkgU17NLOHR05AYE0+Vj3GDPjb8p6nATBGnmZohoIGoX9IxH4+abEMgLZiwHof/6ctZXdHvDi/qk+sb0K+mHFxw8H2r4sEtKIf0yVjPyng6T0/2WysNOqepqPc0WNyWaJYmx14pPaNsDCv61ORGgdBumDd/vxBvQ=="

postgresql:
  enabled: true
  username: "budgetwise"
  password: "changeme"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: budgetwise.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Environment variables
env:
  NODE_ENV: production
  PORT: 3000
  HOSTNAME: "0.0.0.0"

# MongoDB configuration
mongodb:
  enabled: true
  auth:
    enabled: false  # Disable auth for simplicity
  persistence:
    enabled: true
    size: 8Gi
    accessMode: ReadWriteOnce
    storageClass: ""  # Use default storage class
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Database seeding
seed:
  enabled: true
  job:
    restartPolicy: Never
    backoffLimit: 3