---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: {{ include "budgetwise.namespace" . }}
spec:
  encryptedData:
    postgresql-password: {{ .Values.perfin.sealedSecrets.postgresqlPassword | quote }}
    postgresql-username: {{ .Values.perfin.sealedSecrets.postgresqlUsername | quote }}
  template:
    metadata:
      name: postgresql-secret
      namespace: {{ include "budgetwise.namespace" . }}