name: Promote Artifacts

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to promote to'
        required: true
        type: choice
        options:
          - dev
          - prod
      branch:
        description: 'Branch to promote from'
        required: true
        type: choice
        options:
          - main
          - develop
      image_tag:
        description: 'Docker image tag to promote'
        required: true
        type: string
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  re-tag-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set lowercase image name
        run: echo "IMAGE_NAME_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Pull existing image
        run: |
          docker pull ghcr.io/${{ env.IMAGE_NAME_LC }}:${{ inputs.branch }}

      - name: Tag image with new version
        run: |
          docker tag \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}:${{ inputs.branch }} \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}:${{ inputs.image_tag }}

      - name: Push new tag
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}:${{ inputs.image_tag }}
  promote:
    needs: re-tag-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: AbirAahammed/BudgetWise-gitops
          token: ${{ secrets.GIT_REPO_TOKEN }}
          path: gitops

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O yq
          chmod +x yq
          sudo mv yq /usr/local/bin/

      - name: Update values.yaml
        run: |
          cd gitops

          FILE="env/${{ inputs.environment }}/values.yaml"

          echo "Updating $FILE with image tag ${{ inputs.image_tag }}"

          yq e -i 'budgetwise.image.tag = "${{ inputs.image_tag }}"' $FILE

      - name: Commit and push changes
        run: |
          cd gitops
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          git commit -m "promote: ${{ inputs.environment }} → ${{ inputs.image_tag }}"
          git push